//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInventory.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarInventory.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;43&lt;/x&gt;
        ///    &lt;y&gt;156&lt;/y&gt;
        ///    &lt;hp&gt;2&lt;/hp&gt;
        ///    &lt;colour&gt;Yellow&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;99&lt;/x&gt;
        ///    &lt;y&gt;125&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;colour&gt;GreenYellow&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;155&lt;/x&gt;
        ///    &lt;y&gt;94&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;colour&gt;GreenYellow&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;211&lt;/x&gt;
        ///    &lt;y&gt;63&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;colour&gt;GreenYellow&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;267&lt;/x&gt;
        ///    &lt;y&gt;32&lt;/y&gt;
        ///    &lt;hp&gt;1&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XMLFile1 {
            get {
                return ResourceManager.GetString("XMLFile1", resourceCulture);
            }
        }
    }
}
